# serverless.yml

service: serverless-example-with-rollback

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

package:
  excludeDevDependencies: true

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
